export type permissionType =
  | 'CREATE_DOCUMENT'
  | 'READ_DOCUMENT'
  | 'UPDATE_DOCUMENT'
  | 'DELETE_DOCUMENT'
  | 'MANAGE_USERS'
  | 'MANAGE_ROLES'
  | 'MANAGE_TEMPLATES'
  | 'APPROVE_DOCUMENT'
  | 'REVIEW_DOCUMENT'
  | 'SIGN_DOCUMENT'
  | 'PUBLISH_DOCUMENT';
